server:
  port: 8003
spring:
  application:
    name: service-vod
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 50MB
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    nacos:
      server-addr: 159.75.211.245:8848
aliyun:
  vod:
    file:
      keyid: LTAI5tJNEg3C2UpX7wVqTurQ
      keysecret: QWf45WOVHj28sSKfulGcSmTdSRu4Op

