server:
  port: 8001
spring:
  application:
    name: service-edu
  datasource:
    username: coderpwh
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://159.75.211.245:3306/guli?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    nacos:
      server-addr: 159.75.211.245:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

springfox:
  documentation:
    auto-startup: true
    swagger:
      v2:
        use-model-v3: true
    swagger-ui:
      enabled: true

