server:
  port: 8002
spring:
  application:
    name: service-oss

  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
qiniu:
  oss:
#    不区分大小写
    accessKey: r-LHwUZqdvQ-cyEe5AQxCSOujKtatktlowUtVrdJ
    secretKey: E47xoafkir2fbQ3tw0cX8d5mGeaPoB8Elr2PtNiC
    bucket: cdpwh


